MoneyNote/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("cms/", include("cms.urls")),
    path("admin/", admin.site.urls),
]

cms/urls.py
from django.urls import path
from cms import views

app_name = "cms"
urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path("trade/", views.trade_list, name="trade_list"),   #一覧
    path("trade/add/", views.trade_edit, name="trade_add"),  # 登録
    path("trade/mod/<int:id>/", views.trade_edit, name="trade_mod"),  # 修正
    path("trade/del/<int:id>/", views.trade_del, name="trade_del"),   # 削除
    path("trade/export/", views.export, name='export'),
    path("trade/search/", views.trade_search, name="trade_search"),   # 検索
]

cms/models.py
from django.conf import settings
from django.db import models
from django.core.mail import send_mail
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.contrib.auth.base_user import BaseUserManager


if settings.AUTH_USER_MODEL == 'cms.User':
    class UserManager(BaseUserManager):

        use_in_migrations = True

        def _create_user(self, email, password, **extra_fields):
            if not email:
                raise ValueError('The given email must be set')
            email = self.normalize_email(email)

            user = self.model(email=email, **extra_fields)
            user.set_password(password)
            user.save(using=self._db)
            return user

        def create_user(self, email, password=None, **extra_fields):
            extra_fields.setdefault('is_staff', False)
            extra_fields.setdefault('is_superuser', False)
            return self._create_user(email, password, **extra_fields)

        def create_superuser(self, email, password, **extra_fields):
            extra_fields.setdefault('is_staff', True)
            extra_fields.setdefault('is_superuser', True)

            if extra_fields.get('is_staff') is not True:
                raise ValueError('Superuser must have is_staff=True.')
            if extra_fields.get('is_superuser') is not True:
                raise ValueError('Superuser must have is_superuser=True.')

            return self._create_user(email, password, **extra_fields)


    class User(AbstractBaseUser, PermissionsMixin):
        email = models.EmailField(_('email address'), unique=True)
        first_name = models.CharField(_('first name'), max_length=30, blank=True)
        last_name = models.CharField(_('last name'), max_length=150, blank=True)

        is_staff = models.BooleanField(
            _('staff status'),
            default=False,
            help_text=_(
                'Designates whether the user can log into this admin site.'),
        )
        is_active = models.BooleanField(
            _('active'),
            default=True,
            help_text=_(
                'Designates whether this user should be treated as active. '
                'Unselect this instead of deleting accounts.'
            ),
        )
        date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

        objects = UserManager()

        EMAIL_FIELD = 'email'
        USERNAME_FIELD = 'email'
        REQUIRED_FIELDS = []

        class Meta:
            verbose_name = _('user')
            verbose_name_plural = _('users')

        def get_full_name(self):
            full_name = '%s %s' % (self.first_name, self.last_name)
            return full_name.strip()

        def get_short_name(self):
            return self.first_name

        def email_user(self, subject, message, from_email=None, **kwargs):
            send_mail(subject, message, from_email, [self.email], **kwargs)

        @property
        def username(self):
            return self.email


class Trade(models.Model):
    date = models.DateField("日付")
    name = models.CharField("品目名", max_length=255)
    supplier = models.CharField("取引先", max_length=255)
    price = models.FloatField("金額")
    currency = models.CharField("通貨", max_length=3)

cms/forms.py
import bootstrap_datepicker_plus as datetimepicker
from django import forms
from cms.models import Trade, User
import datetime
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm, 
PasswordChangeForm, PasswordResetForm, SetPasswordForm)


CHOICES = (
    ("", "選択肢から選んでください"),
    ("JPY", "円"),
    ("USD", "ドル"),
    ("EUR", "ユーロ"),
    ("GBP", "ポンド")
)


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる

class UserCreateForm(UserCreationForm):
    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email',)
        else:
            fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email', 'first_name', 'last_name')
        else:
            fields = ('username', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class MyPasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class TradeForm(forms.ModelForm):
    class Meta:
        model = Trade
        fields = ("date", "name", "supplier", "price", "currency",)
        widgets = {
            "date": datetimepicker.DatePickerInput(format='%Y-%m-%d',
            options={
                "locale": "ja",
                "dayViewHeaderFormat": "YYYY年 MMMM",
            }),
            "currency": forms.Select(choices=CHOICES),
        }

class SearchForm(forms.Form):
    start = forms.DateField(label = "開始日", required = False, widget = datetimepicker.DatePickerInput(format='%Y-%m-%d',
    options={
        "locale": "ja",
        "dayViewHeaderFormat": "YYYY年 MMMM",
        }))
    end = forms.DateField(label = "終了日", required = False, widget = datetimepicker.DatePickerInput(format='%Y-%m-%d',
    options={
        "locale": "ja",
        "dayViewHeaderFormat": "YYYY年 MMMM",
        }))
    name = forms.CharField(label = "品目名", max_length=255, required = False)
    supplier = forms.CharField(label = "取引先", max_length=255, required = False)
    min_price = forms.FloatField(label = "最低金額", required = False)
    max_price = forms.FloatField(label = "最高金額", required = False)
    currency = forms.CharField(label = "通貨", max_length=3, required = False, widget=forms.Select(choices=CHOICES))

    def clean_end(self):
        end = self.cleaned_data["end"]
        start = self.cleaned_data["start"]
        if end < start:
            raise forms.ValidationError("開始日よりも遅い日付を設定してください")
        return end

    def clean_max_price(self):
        max_price = float(self.cleaned_data["max_price"])
        min_price = float(self.cleaned_data["min_price"])
        if max_price < min_price:
            raise forms.ValidationError("最低金額よりも高い金額を設定してください")
        return max_price

cms/views.py
from django.shortcuts import render, resolve_url
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseBadRequest
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView,
PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import generic
from cms.models import Trade, User
from cms.forms import (TradeForm, SearchForm, UserCreateForm, LoginForm, UserUpdateForm, 
MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm)

import math
import numpy as np
import pandas as pd
import pandas_datareader.data as web
from datetime import timedelta
import datetime
import csv
import urllib

trades = Trade.objects.all().order_by('id')
User = get_user_model()

class Top(generic.TemplateView):
    template_name = "trade_list.html"


class Login(LoginView):
    form_class = LoginForm
    template_name = 'login.html'


class Logout(LoginRequiredMixin, LogoutView):
    template_name = 'trade_list.html'

class UserCreate(generic.CreateView):
    template_name = 'user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': self.request.scheme,
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('cms:user_create_done')


class UserCreateDone(generic.TemplateView):
    template_name = 'user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    template_name = 'user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # 問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    model = User
    template_name = 'user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'user_form.html'

    def get_success_url(self):
        return resolve_url('cms:user_detail', pk=self.kwargs['pk'])

class PasswordChange(PasswordChangeView):
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('cms:password_change_done')
    template_name = 'password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'password_change_done.html'


class PasswordReset(PasswordResetView):
    subject_template_name = 'password_reset/subject.txt'
    email_template_name = 'password_reset/message.txt'
    template_name = 'password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('cms:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    template_name = 'password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    form_class = MySetPasswordForm
    success_url = reverse_lazy('cms:password_reset_complete')
    template_name = 'password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'password_reset_complete.html'

def trade_list(request):
    trades = Trade.objects.all().order_by('id')
    return render(request,
                  "trade_list.html",     # 使用するテンプレート
                  {"trades": trades, "op": 0})         # テンプレートに渡すデータ


def trade_edit(request, id=None):
    if id: # 修正時
        trade = get_object_or_404(Trade, pk=id)
    else:  # 追加時
        trade = Trade()

    if request.method == 'POST':
        form = TradeForm(request.POST, instance=trade)
        if form.is_valid():
            trade = form.save(commit=False)
            trade.save()
            return redirect("cms:trade_list")
    else:
        form = TradeForm(instance=trade)

    return render(request, "trade_edit.html", dict(form=form, id=id))    


def trade_del(request, id):
    trade = get_object_or_404(Trade, pk=id)
    trade.delete()
    return redirect("cms:trade_list")

def export(request):
    global trades
    currency = {0: "DEXJPUS", 1: "DEXUSEU", 2: "DEXUSUK",}
    for trade in trades:
        t = trade.date - timedelta(7)
        t1str = t.strftime('%Y-%m-%d')
        t2str = trade.date.strftime('%Y-%m-%d')
        df = web.DataReader(currency.values(), "fred", t1str, t2str)
        rate = df.values
        try:
            if trade.currency == "USD":
                trade.price = math.ceil(trade.price * rate[0][0])
            elif trade.currency == "EUR":
                trade.price = math.ceil(trade.price * rate[0][0] * rate[0][1])
                trade.currency = "JPY"
            elif trade.currency == "GBP":
                trade.price = math.ceil(trade.price * rate[0][0] * rate[0][2])
                trade.currency = "JPY"
            else:
                pass
        except:
            pass
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=MoneyNote.csv'    
    writer = csv.writer(response)
    writer.writerow(["ID", "日付", "品目名", "取引先", "金額 (円)"])
    for trade in trades:
        writer.writerow([trade.id, trade.date, trade.name, trade.supplier, trade.price])
    return response

def trade_search(request):
    global trades
    if request.method == 'POST':
        form = SearchForm(request.POST)
        start = request.POST["start"]
        end = request.POST["end"]
        name = request.POST["name"]
        supplier = request.POST["supplier"]
        min_price = request.POST["min_price"]
        max_price = request.POST["max_price"]
        currency = request.POST["currency"]

        if start != "":
            trades = trades.filter(date__gte=start)
        else:
            pass
        if end != "":
            trades = trades.filter(date__lte=end)
        else:
            pass
        if name != "":
            trades = trades.filter(name__contains=name)
        else:
            pass
        if supplier != "":
            trades = trades.filter(supplier__contains=supplier)
        else:
            pass
        if min_price != "":
            trades = trades.filter(price__gte=min_price)
        else:
            pass
        if max_price != "":
            trades = trades.filter(price__lte=max_price)
        else:
            pass
        if currency != "":
            trades = trades.filter(currency__contains=currency)
        else:
            pass
        return render(request,
                  "trade_list.html",     # 使用するテンプレート
                  {"trades": trades, "op": 1})         # テンプレートに渡すデータ    
    else:
        form = SearchForm(None)

    return render(request, "trade_search.html", {"form": form})    

cms/templates/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% load i18n static %}

<!DOCTYPE html>{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'cms/css/bootstrap.min.css' %}">
{% block extra_css %}{% endblock %}
<title>{% block title %}My Trades{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'cms:trade_list' %}">Money Note</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li>
            <a class="nav-item nav-link" href="{% url 'cms:user_detail' user.pk %}">ユーザー情報閲覧</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'cms:user_update' user.pk %}">ユーザー情報更新</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'cms:logout' %}">ログアウト</a>
          </li>
          <li>
            <a class="nav-item nav-link" href="{% url 'cms:password_change' %}">パスワードの変更</a>
          </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-item nav-link" href="{% url 'cms:login' %}">
          ログインはこちら
        </a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>  
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
{% block extra_js %}{% endblock %}
</body>
</html>

cms/templates/login.html
{% extends "base.html" %}
{% block title %}ログイン{% endblock title %}
{% block content %}
<h4 class="mt-4 border-bottom">ログイン</h4>
<div class="row">
    <form action="{% url 'cms:login' %}" method="POST">
        {{ form.non_field_errors }}
        {% for field in form %}
            {{ field }}
            {{ field.errors }}
            <hr>
        {% endfor %}
        <button type="submit" class="btn btn-primary" >ログイン</button>
        <input type="hidden" name="next" value="{{ next }}" />
        {% csrf_token %}
        <a href="{% url 'cms:user_create' %}" class="btn btn-primary" >会員登録</a>
    </form>
</div>
{% endblock %}

cms/templates/password_change.html
{% extends "base.html" %}
{% block content %}
<h4 class="mt-4 mb-5 border-bottom">パスワードの変更</h4>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">送信</button>
</form>
{% endblock %}

cms/templates/password_reset_comfirm.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">送信</button>
</form>
{% endblock %}

cms/templates/password_reset_complete.html
{% extends "base.html" %}
{% block content %}
<p>
    パスワード再設定を完了しました。<br>
    <a class="btn btn-primary" href="{% url 'cms:login' %}">ログイン</a>
</p>
{% endblock %}

cms/templates/password_reset_done.html
{% extends "base.html" %}
{% block content %}
<p>
    パスワード再設定用のメールを送信しました。<br>
    メールに記載されているリンクから再設定を行ってください。
</p>
{% endblock %}

cms/templates/password_reset_form.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">送信</button>
</form>
{% endblock %}

cms/templates/trade_edit.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% block title %}取引の編集{% endblock title %}
{% block content %}
    <h4 class="mt-4 mb-5 border-bottom">取引の編集</h4>
    {% if id %}
    <form action="{% url 'cms:trade_mod' id=id %}" method="post">
    {% else %}
    <form action="{% url 'cms:trade_add' %}" method="post">
    {% endif %}
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <button type="submit" class="btn btn-primary">送信</button>
        </div>
      </div>
    </form>
    <a href="{% url 'cms:trade_list' %}" class="btn btn-secondary btn-sm">戻る</a>
{% endblock content %}

cms/templates/trade_list.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}
{% block title %}取引の一覧{% endblock title %}
{% block content %}
    <h4 class="mt-4 border-bottom">取引の一覧</h4>
    <a href="{% url 'cms:trade_search' %}" class="btn btn-primary btn-sm my-3">検索</a>
    {% if op == 0 %}
    <a href="{% url 'cms:trade_add' %}" class="btn btn-secondary btn-sm">追加</a>
    {% else %}
    <a href="{% url 'cms:trade_list' %}" class="btn btn-secondary btn-sm">戻る</a>
    {% endif %}
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">日付</th>
          <th scope="col">品目名</th>
          <th scope="col">取引先</th>
          <th scope="col">金額</th>
          <th scope="col">通貨</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for trade in trades %}
        <tr>
          <th scope="row">{{ trade.id }}</th>
          <td>{{ trade.date }}</td>
          <td>{{ trade.name }}</td>
          <td>{{ trade.supplier }}</td>
          <td>{{ trade.price }}</td>
          <td>{{ trade.currency }}</td>
          <td>
            <a href="{% url 'cms:trade_mod' id=trade.id %}" class="btn btn-outline-primary btn-sm">修正</a>
            <a href="{% url 'cms:trade_del' id=trade.id %}" class="btn btn-outline-danger btn-sm">削除</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <a href="{% url 'cms:export' %}" class="btn btn-secondary btn-sm">出力</a>
{% endblock content %}

cms/templates/user_create.html
{% extends "base.html" %}
{% block content %}
<h4 class="mt-4 mb-5 border-bottom">会員登録</h4>
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">送信</button>
</form>
{% endblock %}

cms/templates/user_create_complete.html
{% extends "base.html" %}
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary" href="{% url 'cms:login' %}">ログイン</a>
</p>
{% endblock %}

cms/templates/user_create_done.html
{% extends "base.html" %}
{% block content %}
<p>
    会員登録確認メールを送信しました。まだ、会員登録は完了していません。<br>
    確認メールを送信しましたので、確認メールに記載されているリンクから本登録を行ってください。
</p>
{% endblock %}

cms/templates/user_detail.html
{% extends "base.html" %}
{% block content %}
<h4 class="mt-4 mb-5 border-bottom">ユーザ情報閲覧</h4>
<table class="table">
    <tbody>
        <tr>
            <th>ユーザー名</th>
            <td>{{ user.username }}</td>
        </tr>
        {% if user.username != user.email %}
        <tr>
            <th>ユーザー名</th>
            <td>{{ user.email }}</td>
        </tr>
        {% endif %}
        <tr>
            <th>姓</th>
            <td>{{ user.last_name }}</td>
        </tr>
        <tr>
            <th>名</th>
            <td>{{ user.first_name }}</td>
        </tr>
    </tbody>
</table>
{% endblock %}

cms/templates/user_form.html
{% extends "base.html" %}
{% block content %}
<h4 class="mt-4 mb-5 border-bottom">ユーザ情報の更新</h4>
<form action="" method="POST">
    {{ form.non_field_errors }}
    <table class="table">
        <tbody>
            {% for field in form %}
                <tr>
                    <th><label for="{{ field.id_for_label }}">{{ field.label }}</label></th>
                    <td>{{ field }} {{ field.errors }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% csrf_token %}
    <button type="submit" class="btn btn-primary" >送信</button>
</form>
{% endblock %}